version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: /home/circleci/go/src/github.com/docker-lvm-plugin
    steps:
      - checkout
      - run: make circleci
      - run: sudo make test
      - run: make -f plugin/Makefile create
